name = "LaserCortex"
version = "0.1.0"
defaultTargets = ["lasercortex"]

[[lean_lib]]
name = "LaserCortex"

[[lean_exe]]
name = "lasercortex"
root = "Main"

[[require]]
name = "mathlib"
path = ".lake/packages/mathlib4"
# Pinned to rev ab5497e460f08b0e35e30b404eba9f317b6eea36

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"
