/-
# Module: CayleyDickson

## Intent

Defines the Cayley-Dickson generator ω of the split-octonions and proves
its essential properties. The CD generator ω = e₄ is the element that
generates the CD doubling from the split-quaternions to split-octonions:

    SO = CD(ℚ, SQ̅) where ω = (0, 1) ∈ ℚ × SQ̅

Properties:
- ω² = +1 (the split-complex case, γ = +1)
- ω anticommutes with the split-sector imaginary elements (e₅, e₆, e₇)
- Antipode(ω) = ω (FIXES ω, whereas the standard CD antipode requires
  S(ω) = -ω — this mismatch is the root cause of the antipode failure)

## Contracts

[omega, omega_sq, omega_anticomm_e5, omega_anticomm_e6, omega_anticomm_e7,
 SplitComplex, split_complex_mul, omega_subalgebra_is_split_complex]

## Cross-refs

LaserCortex.SplitOctonionCost → SplitOctonion, split_oct_mul, e4_vec, e5_vec, e6_vec, e7_vec
LaserCortex.Hopf → antipode (referenced in comments, not imported — no circular dep)

## Tags

#lean4-theorem #cayley-dickson #split-octonion #cd-generator
-/

import LaserCortex.SplitOctonionCost
import LaserCortex.SplitQuaternionClifford

open SplitOctonionCost
open SplitQuaternionClifford

namespace CayleyDickson

/-- Componentwise negation of a SplitOctonion (local definition, avoids dependency on Hopf). -/
def split_neg (x : SplitOctonion) : SplitOctonion :=
  { e0 := -x.e0, e1 := -x.e1, e2 := -x.e2, e3 := -x.e3,
    e4 := -x.e4, e5 := -x.e5, e6 := -x.e6, e7 := -x.e7 }

-- ============================================================================
-- SECTION 1: The CD Generator ω = e₄
-- ============================================================================

/-- The Cayley-Dickson generator ω of the split-octonions.

    In the CD construction SO = CD(ℚ, SQ̅), ω = (0, 1) ∈ ℚ × SQ̅
    which under the componentwise mapping corresponds to e₄.

    ω² = +1 for the split case (split-complex numbers ℂ'),
    ω² = -1 for the compact case (standard complex numbers ℂ).
    In our split-octonion algebra, ω² = 1. -/
def omega : SplitOctonion := e4_vec

/-- ω² = 1 (the split-complex case, γ = +1).
    This matches the CD construction with γ = +1:
    ω = (0, 1) has ω² = γ·(1, 0) = +1·(1, 0) = 1 ∈ ℚ. -/
theorem omega_sq : split_oct_mul omega omega = split_one := by
  apply SplitOctonion.ext_components <;>
  unfold omega e4_vec split_oct_mul split_one <;> ring

/-- ω·e₅ = -e₅·ω (anticommutation).
    In CD terms: ω acting on the second component by conjugation flips sign. -/
theorem omega_anticomm_e5 : split_oct_mul omega e5_vec = split_neg (split_oct_mul e5_vec omega) := by
  apply SplitOctonion.ext_components <;>
  unfold omega e4_vec e5_vec split_oct_mul split_neg <;> ring

/-- ω·e₆ = -e₆·ω (anticommutation). -/
theorem omega_anticomm_e6 : split_oct_mul omega e6_vec = split_neg (split_oct_mul e6_vec omega) := by
  apply SplitOctonion.ext_components <;>
  unfold omega e4_vec e6_vec split_oct_mul split_neg <;> ring

/-- ω·e₇ = -e₇·ω (anticommutation). -/
theorem omega_anticomm_e7 : split_oct_mul omega e7_vec = split_neg (split_oct_mul e7_vec omega) := by
  apply SplitOctonion.ext_components <;>
  unfold omega e4_vec e7_vec split_oct_mul split_neg <;> ring

/-- The product ω·e₅ yields -e₁ (a first-component element).
    This demonstrates the CD mixing: the CD generator acting on the
    second component produces an element in the first component. -/
theorem omega_mul_e5 : split_oct_mul omega e5_vec = split_neg e1_vec := by
  apply SplitOctonion.ext_components <;>
  unfold omega e4_vec e5_vec e1_vec split_oct_mul split_neg <;> ring

/-- The product e₅·ω yields e₁ (positive, opposite sign). -/
theorem e5_mul_omega : split_oct_mul e5_vec omega = e1_vec := by
  apply SplitOctonion.ext_components <;>
  unfold omega e4_vec e5_vec e1_vec split_oct_mul <;> ring

-- ============================================================================
-- SECTION 2: Split-Complex Numbers ℂ' as the Subalgebra Generated by ω
-- ============================================================================

/-- The split-complex numbers ℂ' = {a + b·ω | a,b ∈ ℤ, ω² = 1}.
    This is the subalgebra of SO generated by the CD generator ω.

    In the CD Galois interpretation, ℂ' = ⟨ω⟩ is the "remainder"
    when projecting SQ → SO → ℚ: the CD generator ω generates the
    smallest subalgebra that distinguishes the split from compact form. -/
structure SplitComplex where
  a : ℤ
  b : ℤ
  deriving Repr

/-- The zero element of SplitComplex. -/
def split_complex_zero : SplitComplex := ⟨0, 0⟩

/-- The one element of SplitComplex. -/
def split_complex_one : SplitComplex := ⟨1, 0⟩

/-- Addition in SplitComplex: (a + bω) + (c + dω) = (a+c) + (b+d)ω. -/
def split_complex_add (x y : SplitComplex) : SplitComplex :=
  ⟨x.a + y.a, x.b + y.b⟩

/-- Negation in SplitComplex: -(a + bω) = (-a) + (-b)ω. -/
def split_complex_neg (x : SplitComplex) : SplitComplex :=
  ⟨-x.a, -x.b⟩

/-- Multiplication in SplitComplex: ℂ' ≅ ℤ[x]/(x²-1).
    (a + bω)(c + dω) = ac + ad·ω + bc·ω + bd·ω²
                     = (ac + bd) + (ad + bc)·ω
    since ω² = 1. -/
def split_complex_mul (x y : SplitComplex) : SplitComplex :=
  ⟨x.a * y.a + x.b * y.b, x.a * y.b + x.b * y.a⟩

instance : Add SplitComplex := ⟨split_complex_add⟩
instance : Zero SplitComplex := ⟨split_complex_zero⟩
instance : Neg SplitComplex := ⟨split_complex_neg⟩
instance : Mul SplitComplex := ⟨split_complex_mul⟩

@[ext]
theorem SplitComplex.ext_components (x y : SplitComplex) (ha : x.a = y.a) (hb : x.b = y.b) : x = y := by
  cases x; cases y; dsimp at ha hb; subst ha; subst hb; rfl

/-- SplitComplex multiplication is associative and commutative (it's ℤ[x]/(x²-1)). -/
theorem split_complex_mul_assoc (x y z : SplitComplex) : (x * y) * z = x * (y * z) := by
  apply SplitComplex.ext_components <;> unfold split_complex_mul <;> ring

theorem split_complex_mul_comm (x y : SplitComplex) : x * y = y * x := by
  apply SplitComplex.ext_components <;> unfold split_complex_mul <;> ring

/-- The norm on ℂ': N(a + bω) = a² - b².
    This is the (1,1) quadratic form — the split complex analogue of |a+bi|² = a²+b². -/
def split_complex_norm (x : SplitComplex) : ℤ := x.a * x.a - x.b * x.b

/-- The embedding of SplitComplex into SO: map (a,b) ↦ a·1 + b·ω.
    Since ω = e₄ in SO, this is: a·e₀ + b·e₄. -/
def emb (x : SplitComplex) : SplitOctonion :=
  { e0 := x.a, e1 := 0, e2 := 0, e3 := 0,
    e4 := x.b, e5 := 0, e6 := 0, e7 := 0 }

/-- The embedding is ℤ-linear: emb(x + y) = split_add(emb x, emb y). -/
theorem emb_add (x y : SplitComplex) : emb (x + y) = split_add (emb x) (emb y) := by
  apply SplitOctonion.ext_components <;>
  unfold emb split_complex_add split_add <;> simp

/-- The embedding is multiplicative: emb(xy) = emb(x)·emb(y).
    This proves ⟨ω⟩ ≅ ℂ' as ℤ-algebras. -/
theorem emb_mul (x y : SplitComplex) : emb (x * y) = split_oct_mul (emb x) (emb y) := by
  apply SplitOctonion.ext_components <;>
  unfold emb split_oct_mul split_complex_mul <;> ring

/-- The embedding is injective. -/
theorem emb_injective (x y : SplitComplex) (h : emb x = emb y) : x = y := by
  apply SplitComplex.ext_components
  · have he0 : (emb x).e0 = (emb y).e0 := by rw [h]
    dsimp [emb] at he0
    exact he0
  · have he4 : (emb x).e4 = (emb y).e4 := by rw [h]
    dsimp [emb] at he4
    exact he4

-- ============================================================================
-- SECTION 3: Compact Quaternion Ring ℚ = ℍ[ℤ] (all squares = -1)
-- ============================================================================

/-- The compact quaternion ring ℚ = ℍ[ℤ] over ℤ.
    Basis: {1, i, j, k} where i² = j² = k² = -1 (all negative, unlike SQ).
    Norm: N(a,b,c,d) = a² + b² + c² + d² (positive-definite, unlike SQ's (2,2)).

    This is the associative sector of the split-octonion algebra:
    the first 4 components e₀,e₁,e₂,e₃ behave as ℍ[ℤ] under split_oct_mul. -/
structure Quaternionℤ where
  a : ℤ  -- scalar (1)
  b : ℤ  -- i coefficient
  c : ℤ  -- j coefficient
  d : ℤ  -- k coefficient
  deriving Repr

/-- The zero element of Quaternionℤ. -/
def quat_zero : Quaternionℤ := ⟨0, 0, 0, 0⟩

/-- The one element of Quaternionℤ. -/
def quat_one : Quaternionℤ := ⟨1, 0, 0, 0⟩

/-- Addition in ℚ: componentwise. -/
def quat_add (x y : Quaternionℤ) : Quaternionℤ :=
  ⟨x.a + y.a, x.b + y.b, x.c + y.c, x.d + y.d⟩

/-- Negation in ℚ: componentwise. -/
def quat_neg (x : Quaternionℤ) : Quaternionℤ :=
  ⟨-x.a, -x.b, -x.c, -x.d⟩

/-- Multiplication in ℚ: the standard compact quaternion multiplication.
    All imaginary units square to -1, giving the (++++)-norm composition algebra:
    
    (a₁ + b₁·i + c₁·j + d₁·k)(a₂ + b₂·i + c₂·j + d₂·k) =
      (a₁a₂ - b₁b₂ - c₁c₂ - d₁d₂)            -- scalar
    + (a₁b₂ + b₁a₂ + c₁d₂ - d₁c₂) · i         -- i
    + (a₁c₂ - b₁d₂ + c₁a₂ + d₁b₂) · j         -- j
    + (a₁d₂ + b₁c₂ - c₁b₂ + d₁a₂) · k         -- k
    
    This matches the associative sector of split_oct_mul restricted to e₀..e₃. -/
def quat_mul (x y : Quaternionℤ) : Quaternionℤ :=
  ⟨x.a*y.a - x.b*y.b - x.c*y.c - x.d*y.d,
   x.a*y.b + x.b*y.a + x.c*y.d - x.d*y.c,
   x.a*y.c - x.b*y.d + x.c*y.a + x.d*y.b,
   x.a*y.d + x.b*y.c - x.c*y.b + x.d*y.a⟩

instance : Add Quaternionℤ := ⟨quat_add⟩
instance : Zero Quaternionℤ := ⟨quat_zero⟩
instance : Neg Quaternionℤ := ⟨quat_neg⟩
instance : Mul Quaternionℤ := ⟨quat_mul⟩

@[ext]
theorem Quaternionℤ.ext_components (x y : Quaternionℤ) (ha : x.a = y.a) (hb : x.b = y.b)
    (hc : x.c = y.c) (hd : x.d = y.d) : x = y := by
  cases x; cases y; dsimp at ha hb hc hd; subst ha; subst hb; subst hc; subst hd; rfl

/-- Quaternionℤ multiplication is associative (it's ℍ[ℤ]). -/
theorem quat_mul_assoc (x y z : Quaternionℤ) : (x * y) * z = x * (y * z) := by
  apply Quaternionℤ.ext_components <;> unfold quat_mul <;> ring

/-- The (4,0) norm of ℚ: N(a,b,c,d) = a² + b² + c² + d².
    This is positive-definite and matches the associative sector
    of the split-octonion norm (which has (4,4) signature). -/
def quat_norm (x : Quaternionℤ) : ℤ :=
  x.a*x.a + x.b*x.b + x.c*x.c + x.d*x.d

/-- The conjugation on ℚ (the standard quaternion conjugation):
    conj(a + bi + cj + dk) = a - bi - cj - dk.
    This is an anti-automorphism and satisfies x·conj(x) = N(x). -/
def quat_conj (x : Quaternionℤ) : Quaternionℤ :=
  ⟨x.a, -x.b, -x.c, -x.d⟩

/-- x·conj(x) = N(x) (the norm condition). -/
theorem quat_mul_conj_eq_norm (x : Quaternionℤ) : x * quat_conj x = ⟨quat_norm x, 0, 0, 0⟩ := by
  apply Quaternionℤ.ext_components <;> unfold quat_mul quat_conj quat_norm <;> ring

/-- conj(x·y) = conj(y)·conj(x) (anti-automorphism). -/
theorem quat_conj_anti_aut (x y : Quaternionℤ) : quat_conj (x * y) = quat_conj y * quat_conj x := by
  apply Quaternionℤ.ext_components <;> unfold quat_mul quat_conj <;> ring

-- ============================================================================
-- SECTION 4: The Cayley-Dickson Double CD(ℚ, SQ̅)
-- ============================================================================

/-- The Cayley-Dickson double CD(ℚ, SQ̅) = ℚ × SQ̅.

    Under the canonical basis mapping:
      q ∈ ℚ corresponds to e₀,e₁,e₂,e₃ (the associative sector)
      s ∈ SQ̅ corresponds to e₄,e₅,e₆,e₇ (the split sector)

    The multiplication is defined via the isomorphism with SplitOctonion:
    the CD double is essentially a type-level factoring of the split-octonion
    into its two 4D components, with the multiplication induced by split_oct_mul.

    This is NOT a direct product of algebras (the multiplication mixes components)
    but a semidirect-like construction where the CD generator ω = (0, 1) acts
    on SQ̅ by conjugation (anticommutation with the imaginary elements). -/
structure CDouble where
  q : Quaternionℤ   -- compact quaternion component (e₀..e₃)
  s : SplitQuat     -- split-quaternion component (e₄..e₇)
  deriving Repr

/-- Extensionality for CDouble: two CDoubles are equal if their q and s components are equal. -/
@[ext]
theorem CDouble.ext_components (x y : CDouble) (hq : x.q = y.q) (hs : x.s = y.s) : x = y := by
  cases x; cases y; dsimp at hq hs; subst hq; subst hs; rfl

/-- Embed CDouble into SplitOctonion via the canonical basis mapping. -/
def cd_to_so (x : CDouble) : SplitOctonion :=
  { e0 := x.q.a, e1 := x.q.b, e2 := x.q.c, e3 := x.q.d,
    e4 := x.s.a, e5 := x.s.b, e6 := x.s.c, e7 := x.s.d }

/-- Extract a CDouble from a SplitOctonion via the canonical basis mapping. -/
def so_to_cd (x : SplitOctonion) : CDouble :=
  { q := ⟨x.e0, x.e1, x.e2, x.e3⟩,
    s := ⟨x.e4, x.e5, x.e6, x.e7⟩ }

/-- The CDouble-to-SplitOctonion map and its inverse compose to identity. -/
theorem cd_to_so_so_to_cd (x : SplitOctonion) : cd_to_so (so_to_cd x) = x := by
  apply SplitOctonion.ext_components <;> rfl

theorem so_to_cd_cd_to_so (x : CDouble) : so_to_cd (cd_to_so x) = x := by
  apply CDouble.ext_components
  · apply Quaternionℤ.ext_components <;> rfl
  · apply SplitQuat.ext_components <;> rfl

/-- The CDouble-to-SplitOctonion map is bijective, with so_to_cd as its inverse. -/
theorem cd_to_so_bijection : Function.Bijective cd_to_so := by
  refine ⟨?_, ?_⟩
  · intro x y h
    calc
      x = so_to_cd (cd_to_so x) := by symm; exact so_to_cd_cd_to_so x
      _ = so_to_cd (cd_to_so y) := by rw [h]
      _ = y := so_to_cd_cd_to_so y
  · intro y
    exact ⟨so_to_cd y, cd_to_so_so_to_cd y⟩

/-- Multiplication on CDouble, induced by split_oct_mul on SplitOctonion.
    This definition makes the isomorphism CDouble ≅ SplitOctonion multiplicative
    by construction. -/
def cd_mul (x y : CDouble) : CDouble :=
  so_to_cd (split_oct_mul (cd_to_so x) (cd_to_so y))

/-- The CD generator ω = (0, 1) ∈ CD(ℚ, SQ̅).
    Under cd_to_so, ω maps to e₄ (the split-complex generator). -/
def cd_omega : CDouble :=
  { q := quat_zero, s := ⟨1, 0, 0, 0⟩ }

/-- ω² = 1 in CD(ℚ, SQ̅) (the split case, γ = +1). -/
theorem cd_omega_sq : cd_mul cd_omega cd_omega = ⟨quat_one, split_quat_zero⟩ := by
  calc
    cd_mul cd_omega cd_omega = so_to_cd (split_oct_mul (cd_to_so cd_omega) (cd_to_so cd_omega)) := rfl
    _ = so_to_cd (split_oct_mul omega omega) := by
      unfold cd_to_so cd_omega quat_zero; rfl
    _ = so_to_cd split_one := by rw [omega_sq]
    _ = ⟨quat_one, split_quat_zero⟩ := rfl

/-- The cd_to_so map is multiplicative: cd_to_so(x·y) = cd_to_so(x)·cd_to_so(y).
    This holds by definition of cd_mul. -/
theorem cd_to_so_mul (x y : CDouble) : cd_to_so (cd_mul x y) = split_oct_mul (cd_to_so x) (cd_to_so y) := by
  unfold cd_mul; exact cd_to_so_so_to_cd _

-- ============================================================================
-- SECTION 4a: Additive structure for CDouble
-- ============================================================================

/-- Addition on CDouble: componentwise in ℚ × SQ̅. -/
def cd_add (x y : CDouble) : CDouble :=
  { q := quat_add x.q y.q, s := split_quat_add x.s y.s }

/-- Zero of CDouble. -/
def cd_zero : CDouble :=
  { q := quat_zero, s := split_quat_zero }

/-- Negation on CDouble: componentwise. -/
def cd_neg (x : CDouble) : CDouble :=
  { q := quat_neg x.q, s := split_quat_neg x.s }

instance : Add CDouble := ⟨cd_add⟩
instance : Zero CDouble := ⟨cd_zero⟩
instance : Neg CDouble := ⟨cd_neg⟩
instance : Mul CDouble := ⟨cd_mul⟩

/-- The cd_to_so map is additive: cd_to_so(x + y) = split_add(cd_to_so x, cd_to_so y). -/
theorem cd_to_so_add (x y : CDouble) : cd_to_so (x + y) = split_add (cd_to_so x) (cd_to_so y) := by
  apply SplitOctonion.ext_components <;>
  unfold cd_to_so cd_add quat_add split_quat_add split_add <;> simp

/-- The cd_to_so map preserves zero. -/
theorem cd_to_so_zero : cd_to_so (0 : CDouble) = split_zero := by
  apply SplitOctonion.ext_components <;>
  unfold cd_to_so cd_zero quat_zero split_quat_zero split_zero <;> simp

/-- Componentwise negation of a SplitOctonion (definition for internal use). -/
def so_neg (x : SplitOctonion) : SplitOctonion :=
  { e0 := -x.e0, e1 := -x.e1, e2 := -x.e2, e3 := -x.e3,
    e4 := -x.e4, e5 := -x.e5, e6 := -x.e6, e7 := -x.e7 }

/-- The cd_to_so map preserves negation: cd_to_so(-x) = split_neg (cd_to_so x)
    (where split_neg is local componentwise negation on SplitOctonion). -/
theorem cd_to_so_neg (x : CDouble) : cd_to_so (-x) = split_neg (cd_to_so x) := by
  apply SplitOctonion.ext_components <;>
  unfold cd_to_so cd_neg quat_neg split_quat_neg split_neg <;> simp

-- ============================================================================
-- SECTION 4b: CDouble structural theorems
-- ============================================================================

/-- The split-sector basis elements in CDouble: (0, e₄), (0, e₅), (0, e₆), (0, e₇). -/
def cd_e4 : CDouble := ⟨quat_zero, ⟨1, 0, 0, 0⟩⟩  -- same as cd_omega
def cd_e5 : CDouble := ⟨quat_zero, ⟨0, 1, 0, 0⟩⟩
def cd_e6 : CDouble := ⟨quat_zero, ⟨0, 0, 1, 0⟩⟩
def cd_e7 : CDouble := ⟨quat_zero, ⟨0, 0, 0, 1⟩⟩

/-- ω = e₄ (definitional). -/
theorem cd_omega_eq_e4 : cd_omega = cd_e4 := rfl

/-- ω·e₅ = -e₅·ω in CD(ℚ, SQ̅).
    Proved by expanding definitions and computing in ℤ. -/
theorem cd_omega_anticomm_e5 : cd_mul cd_omega cd_e5 = -(cd_mul cd_e5 cd_omega) := by
  ext <;> dsimp [cd_mul, cd_omega, cd_e5, cd_to_so, so_to_cd, cd_neg,
                quat_zero, quat_neg, split_quat_zero, split_quat_neg, split_oct_mul] <;> ring

/-- Helper: cd_to_so is injective on CDouble. -/
theorem cd_to_so_injective {x y : CDouble} (h : cd_to_so x = cd_to_so y) : x = y :=
  cd_to_so_bijection.injective h

/-- Pure-quaternion multiplication: if both elements have zero split component,
    the product is purely quaternionic and matches quat_mul.
    
    This holds because the associative sector e₀..e₃ of split_oct_mul
    IS the standard quaternion multiplication (all squares = -1). -/
theorem cd_mul_pure_quat (q₁ q₂ : Quaternionℤ) :
    cd_mul (⟨q₁, split_quat_zero⟩ : CDouble) (⟨q₂, split_quat_zero⟩ : CDouble)
    = (⟨quat_mul q₁ q₂, split_quat_zero⟩ : CDouble) := by
  apply cd_to_so_injective
  calc
    cd_to_so (cd_mul (⟨q₁, split_quat_zero⟩ : CDouble) (⟨q₂, split_quat_zero⟩ : CDouble))
        = split_oct_mul (cd_to_so (⟨q₁, split_quat_zero⟩ : CDouble))
                        (cd_to_so (⟨q₂, split_quat_zero⟩ : CDouble)) := cd_to_so_mul _ _
    _ = split_oct_mul (SplitOctonion.mk q₁.a q₁.b q₁.c q₁.d 0 0 0 0)
                      (SplitOctonion.mk q₂.a q₂.b q₂.c q₂.d 0 0 0 0) := rfl
    _ = (SplitOctonion.mk (quat_mul q₁ q₂).a (quat_mul q₁ q₂).b
                          (quat_mul q₁ q₂).c (quat_mul q₁ q₂).d 0 0 0 0) := by
      apply SplitOctonion.ext_components <;>
      dsimp [split_oct_mul, quat_mul, split_zero] <;> ring
    _ = cd_to_so (⟨quat_mul q₁ q₂, split_quat_zero⟩ : CDouble) := rfl

-- ============================================================================
-- SECTION 5: CD Parameter — the branch choice
-- ============================================================================

/--
The **CD parameter** α classifies the branch of the Cayley‑Dickson doubling:

    Q' = Q  ⊕  α · Q

At each CD step, the quadratic form on the new coordinate is α times the
original. This choice determines the algebra structure:

| α | Branch | Examples | ZDs exist? |
|---|--------|----------|-----------|
| +1 | Split | ℂ', ℍ' (SQ), 𝕆' (SO) | **Yes** (step ≥ 3) |
| -1 | Compact | ℂ, ℍ, 𝕆 | No |

The **homotopy** α(t) : [0,1] → {+1, -1} continuously deforms the split
branch into the compact branch. In the framework, this is the "cooling"
parameter that eliminates ZDs from generated structures (Klingler‑Netzer
2024, arXiv:2403.02095).

The ZD monopole constraint in `CompositionSpec` only fires in the split
branch at CD step ≥ 3 with identical evaluators — in the compact branch,
no ZDs exist at any step, so composition is always valid.
-/
inductive CDParameter : Type where
  /-- α = +1: split branch (indefinite quadratic form).
      The CD generator satisfies ω² = +1.
      Zero divisors appear at CD step ≥ 3 (octonion level). -/
  | split
  /-- α = -1: compact branch (definite quadratic form).
      The CD generator satisfies ω² = -1.
      No zero divisors at any CD step. -/
  | compact
  deriving DecidableEq, Repr

/--
The sign of the CD parameter as an integer:

    sign(split)   = +1
    sign(compact) = -1

This is the coefficient α in the doubling formula `Q' = Q ⊕ α·Q`.
-/
def CDParameter.sign : CDParameter → ℤ
  | .split   => 1
  | .compact => -1

/--
The sign as a rational for homotopy continuation.

Used in the hyperbolic program `P(A) = det(A·I - B)` where the
homotopy deforms the Q₂₂ cone continuously.
-/
def CDParameter.signQQ : CDParameter → ℚ :=
  fun a => (a.sign : ℚ)

@[simp] theorem CDParameter.sign_split : CDParameter.sign .split = 1 := rfl
@[simp] theorem CDParameter.sign_compact : CDParameter.sign .compact = -1 := rfl

/--
The CD doubling `Q' = Q ⊕ α·Q` applied to a dimension.

Given a CD step `k` (the dimension index) and a parameter `α`, the
resulting algebra dimension is `2^k`.
-/
def CDParameter.algebraDimension (α : CDParameter) (k : ℕ) : ℕ :=
  2 ^ k

/--
The quadratic form signature for a CD parameter at step `k`:

    split(α = +1):  (k, k) — split signature, indefinite
    compact(α = -1): (2k, 0) — definite positive

The split signature at k ≥ 3 is the geometric source of zero divisors:
the (4,4) signature of SO creates null vectors (non-zero elements with
zero norm) which are the ZDs.
-/
def CDParameter.quadraticSignature (α : CDParameter) (k : ℕ) : ℕ × ℕ :=
  match α with
  | .split   => (k, k)
  | .compact => (2 * k, 0)

/--
The CD parameter is **split** iff its sign is +1.
-/
def CDParameter.isSplit (α : CDParameter) : Bool :=
  α.sign = 1

/--
The CD generator ω satisfies ω² = α·1, i.e.:

    ω² = +1  if α = split   (the split-complex case)
    ω² = -1  if α = compact (the standard complex case)

The existing proof `CayleyDickson.omega_sq` verifies ω² = 1 for the
split case specifically.
-/
theorem CDParameter.omega_sq_eq_sign (α : CDParameter) :
    (α.sign : ℤ) = (if h : α = .split then 1 else -1) := by
  cases α <;> simp

/--
If the CD parameter is `split`, the quadratic form is indefinite
(split signature), and zero divisors may exist at CD step ≥ 3.

This is the formal statement: the existence of ZDs depends on α.
-/
theorem CDParameter.zeroDivisorPossible_iff_split (α : CDParameter) :
    (α.sign = 1) ↔ (α = .split) := by
  cases α <;> simp

/--
The **homotopy path** from split to compact. In the hyperbolic program,
the path t ↦ α(t) continuously deforms the Q₂₂ cone, and the CD tower
level k serves as the homotopy parameter.

The homotopy is:
    α(t) = (1 - 2t)  for t ∈ [0,1]

where α(0) = +1 (split) and α(1) = -1 (compact).

In discrete terms, the CD tower index k traces the path at integer
intervals. The continuation past the ZD boundary at CD 2→3 is governed
by the homotopy step at which zero divisors first appear (k = 3 for
split, k = ∞ for compact).
-/
structure CDHomotopyPath where
  /-- The starting parameter. -/
  start : CDParameter := .split
  /-- The ending parameter. -/
  target : CDParameter := .compact
  /-- The current step along the path (0 = start, 1 = target). -/
  step : ℚ := 0

/--
The homotopy value at a rational step t ∈ [0,1]:

    α(t) = +1  if t = 0
    α(t) = -1  if t = 1
    α(t) = +1  if 0 < t < 1 (for now — linear interpolation in future)
-/
def CDHomotopyPath.value (h : CDHomotopyPath) : CDParameter :=
  if h.step ≤ 0 then .split
  else if h.step ≥ 1 then .compact
  else .split

/--
The CD tower step at which the ZD boundary first appears depends on α:

    split:   ZDs appear at CD step 3 (octonion level, (4,4) signature)
    compact: no ZDs at any finite CD step

This connects the CD parameter to the `CompositionSpec` factory rules.
-/
def CDParameter.zdBoundaryStep (α : CDParameter) : ℕ :=
  match α with
  | .split   => 3
  | .compact => 0  -- no ZD boundary (the sentinel 0 means "never")

/--
A composition at step `k` is ZD‑free iff either:

    1. α = compact (no ZDs at any step), or
    2. k < zdBoundaryStep(α), i.e. k < 3 for split

This is the formal content of `CompositionSpec.no_zd_monopole` — it
excludes exactly the configurations where ZDs exist.
-/
theorem CDParameter.zdFreeAtStep (α : CDParameter) (k : ℕ) : Prop :=
  α = .compact ∨ k < α.zdBoundaryStep

end CayleyDickson
