#!/usr/bin/env python3
"""Analyse the linguistic bridge between the bge-m3 embedding space and the
PROV-O OWL ontology.

The question: when we assign a phrase to a CSG category via embedding cosine
similarity to anchor texts, does the result actually align with what PROV-O
*means* by the corresponding class? Or is the embedding capturing surface
features that don't correspond to the ontology's formal semantics?

Method:
  1. Extract ALL PROV-O class/property definitions from the OWL file.
  2. Embed the PROV-O definitions + our anchor texts + a sample of trace
     phrases.
  3. Compute three matrices:
     a) Our 6 categories (anchor centroid) × 6 mapped PROV-O classes
     b) Our 6 categories (anchor centroid) × ALL PROV-O classes (find nearest)
     c) Sample trace phrases × our 6 categories × PROV-O classes
  4. Linguistic analysis: extract verbs, nouns, sentence patterns from both
     PROV-O definitions and anchor texts. Compare POS distributions.
  5. Report mismatches and corrected mappings.

Usage:
    python3 scripts/analyse_provo_embedding.py
"""
from __future__ import annotations

import json
import os
import re
import sys
import time
import urllib.request
from collections import Counter
from typing import Any, Dict, List, Optional, Tuple

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ═══════════════════════════════════════════════════════════════════════
# 1. PROV-O definitions extracted from the OWL file
# ═══════════════════════════════════════════════════════════════════════

# Hardcoded from manual reading of /tmp/prov-o.owl — the :definition and
# rdfs:comment fields for each class and property.
PROVO_CLASSES = {
    "Activity": {
        "definition": "An activity is something that occurs over a period of time and acts upon or with entities; it may include consuming, processing, transforming, modifying, relocating, using, or generating entities.",
        "category": "starting-point",
        "component": "entities-activities",
    },
    "Agent": {
        "definition": "An agent is something that bears some form of responsibility for an activity taking place, for the existence of an entity, or for another agent's activity.",
        "category": "starting-point",
        "component": "agents-responsibility",
    },
    "Entity": {
        "definition": "An entity is a physical, digital, conceptual, or other kind of thing with some fixed aspects; entities may be real or imaginary.",
        "category": "starting-point",
        "component": "entities-activities",
    },
    "Plan": {
        "definition": "A plan is an entity that represents a set of actions or steps intended by one or more agents to achieve some goals.",
        "rdfs_comment": "There exist no prescriptive requirement on the nature of plans, their representation, the actions or steps they consist of, or their intended goals. Since plans may evolve over time, it may become necessary to track their provenance, so plans themselves are entities.",
        "category": "expanded",
        "component": "agents-responsibility",
    },
    "Role": {
        "definition": "A role is the function of an entity or agent with respect to an activity, in the context of a usage, generation, invalidation, association, start, and end.",
        "category": "qualified",
        "component": "agents-responsibility",
    },
    "Derivation": {
        "definition": "A derivation is a transformation of an entity into another, an update of an entity resulting in a new one, or the construction of a new entity based on a pre-existing entity.",
        "rdfs_comment": "An instance of prov:Derivation provides additional descriptions about the binary prov:wasDerivedFrom relation from some derived prov:Entity to another prov:Entity from which it was derived.",
        "category": "qualified",
        "component": "derivations",
    },
    "Generation": {
        "definition": "Generation is the completion of production of a new entity by an activity. This entity did not exist before generation and becomes available for usage after this generation.",
        "category": "qualified",
        "component": "entities-activities",
    },
    "Usage": {
        "definition": "Usage is the beginning of utilizing an entity by an activity. Before usage, the activity had not begun to utilize this entity and could not have been affected by the entity.",
        "category": "qualified",
        "component": "entities-activities",
    },
    "Communication": {
        "definition": "Communication is the exchange of an entity by two activities, one activity using the entity generated by the other.",
        "category": "qualified",
        "component": "entities-activities",
    },
    "Start": {
        "definition": "Start is when an activity is deemed to have been started by an entity, known as trigger. The activity did not exist before its start. Any usage, generation, or invalidation involving an activity follows the activity's start.",
        "category": "qualified",
        "component": "entities-activities",
    },
    "End": {
        "definition": "End is when an activity is deemed to have been ended by an entity, known as trigger. The activity no longer exists after its end.",
        "category": "qualified",
        "component": "entities-activities",
    },
    "Invalidation": {
        "definition": "Invalidation is the start of the destruction, cessation, or expiry of an existing entity by an activity. The entity is no longer available for use after invalidation.",
        "category": "qualified",
        "component": "entities-activities",
    },
    "Association": {
        "definition": "An activity association is an assignment of responsibility to an agent for an activity, indicating that the agent had a role in the activity. It further allows for a plan to be specified, which is the plan intended by the agent to achieve some goals in the context of this activity.",
        "category": "qualified",
        "component": "agents-responsibility",
    },
    "Attribution": {
        "definition": "Attribution is the ascribing of an entity to an agent. When an entity e is attributed to agent ag, entity e was generated by some unspecified activity that in turn was associated to agent ag.",
        "category": "qualified",
        "component": "agents-responsibility",
    },
    "Delegation": {
        "definition": "Delegation is the assignment of authority and responsibility to an agent to carry out a specific activity as a delegate or representative, while the agent it acts on behalf of retains some responsibility for the outcome.",
        "category": "qualified",
        "component": "agents-responsibility",
    },
    "Collection": {
        "definition": "A collection is an entity that provides a structure to some constituents, which are themselves entities.",
        "category": "expanded",
        "component": "collections",
    },
    "Bundle": {
        "definition": "A bundle is a named set of provenance descriptions, and is itself an Entity, so allowing provenance of provenance to be expressed.",
        "category": "expanded",
    },
    "Location": {
        "definition": "A location can be an identifiable geographic place, but it can also be a non-geographic place such as a directory, row, or column.",
        "category": "expanded",
    },
    "Influence": {
        "definition": "Influence is the capacity of an entity, activity, or agent to have an effect on the character, development, or behavior of another by means of usage, start, end, generation, invalidation, communication, derivation, attribution, association, or delegation.",
        "category": "qualified",
    },
    "InstantaneousEvent": {
        "definition": "The PROV data model is implicitly based on a notion of instantaneous events that mark transitions in the world. Events include generation, usage, or invalidation of entities, as well as starting or ending of activities.",
        "category": "qualified",
    },
    "Organization": {
        "definition": "An organization is a social or legal institution such as a company, society, etc.",
        "category": "expanded",
    },
    "Person": {
        "definition": "Person agents are people.",
        "category": "expanded",
    },
    "SoftwareAgent": {
        "definition": "A software agent is running software.",
        "category": "expanded",
    },
    "Revision": {
        "definition": "A revision is a derivation for which the resulting entity is a revised version of some original. The resulting entity contains substantial content from the original.",
        "category": "qualified",
    },
    "Quotation": {
        "definition": "A quotation is the repeat of some or all of an entity, such as text or image, by someone who may or may not be its original author. Quotation is a particular case of derivation.",
        "category": "qualified",
    },
    "PrimarySource": {
        "definition": "A primary source for a topic refers to something produced by some agent with direct experience and knowledge about the topic, at the time of the topic's study, without benefit from hindsight.",
        "category": "qualified",
    },
    "EmptyCollection": {
        "definition": "An empty collection is a collection without members.",
        "category": "expanded",
    },
}

PROVO_PROPERTIES = {
    "used": "A prov:Entity that was used by this prov:Activity.",
    "wasGeneratedBy": "An entity was generated by an activity.",
    "wasInformedBy": "An activity a2 is dependent on or informed by another activity a1, by way of some unspecified entity that is generated by a1 and used by a2.",
    "wasAssociatedWith": "An prov:Agent that had some responsibility for the occurrence of this prov:Activity.",
    "wasAttributedTo": "Attribution is the ascribing of an entity to an agent.",
    "wasDerivedFrom": "A derivation is a transformation of an entity into another, an update of an entity resulting in a new one, or the construction of a new entity based on a pre-existing entity.",
    "actedOnBehalfOf": "An object property to express the accountability of an agent towards another agent. The subordinate agent acted on behalf of the responsible agent in an actual activity.",
    "hadPlan": "The optional Plan adopted by an Agent in Association with some Activity.",
    "hadRole": "The optional Role that an Entity assumed in the context of an Activity.",
    "hadMember": "A collection had an entity as member.",
    "specializationOf": "An entity that is a specialization of another shares all aspects of the latter, and additionally presents more specific aspects of the same thing.",
    "alternateOf": "Two alternate entities present aspects of the same thing.",
    "wasStartedBy": "Start is when an activity is deemed to have started. A start may refer to an entity, known as trigger, that initiated the activity.",
    "wasEndedBy": "End is when an activity is deemed to have ended. An end may refer to an entity, known as trigger, that terminated the activity.",
    "wasInvalidatedBy": "An entity was invalidated by an activity.",
    "wasRevisionOf": "A revision is a derivation that revises an entity into a revised version.",
    "wasQuotedFrom": "An entity is derived from an original entity by copying some or all of it.",
    "hadPrimarySource": "A particular case of wasDerivedFrom that aims to give credit to the source that originated some information.",
}

# ═══════════════════════════════════════════════════════════════════════
# 2. Our CSG category anchors
# ═══════════════════════════════════════════════════════════════════════

CSG_CATEGORIES = {
    "temporalMonad": {
        "asserted_provo": "Plan",
        "anchors": [
            "Let me begin by exploring the problem space and understanding what we are working with.",
            "I should start by taking stock of the current situation before proceeding.",
            "I need to first understand the context and constraints before making changes.",
            "Let us now turn to the next step in the reasoning process.",
            "I will now examine the structure of this problem more carefully.",
        ],
    },
    "computationAction": {
        "asserted_provo": "Activity",
        "anchors": [
            "Run the experiment to compute the result and produce concrete output data.",
            "Execute the verification tool to check whether the certificate contraction path is valid.",
            "Parse the input file and build the output structure from the parsed components.",
            "Search the codebase for all references to this function and list the results.",
            "Lift the inference into the formal layer by calling the bridge lift operation.",
            "Ground the certificate back into the decision layer by decomposing the contraction path.",
        ],
    },
    "scope": {
        "asserted_provo": "Role",
        "anchors": [
            "Run a targeted experiment focusing only on the specific module that is failing.",
            "First, check the most critical constraint before expanding the search.",
            "Carefully examine exactly the boundary condition where the error occurs.",
            "Limit the search to precisely the files that were modified in this commit.",
            "Apply this change only to the specific case mentioned, not globally.",
        ],
    },
    "exploration": {
        "asserted_provo": "Entity",
        "anchors": [
            "Investigate the Tamari lattice contraction structure to understand how trees contract.",
            "Explore the proof architecture and understand how the theorems connect to each other.",
            "Understand the codebase structure and how the different modules interact.",
            "Examine what happens when the friction barrier is crossed at the CD 2 to 3 boundary.",
            "Look into the algebraic structure of the split octonion and its basis vectors.",
            "Study how the generation and collapse duality produces candidate structures.",
        ],
    },
    "idempotentTarget": {
        "asserted_provo": "Agent",
        "anchors": [
            "I really want to make sure this is correct before moving forward.",
            "The key insight is definitely that the certificate must verify independently.",
            "This is certainly the right approach because the contraction path is decidable.",
            "I am confident that this result holds and the proof is complete.",
            "This must be exactly right — the system cannot proceed without certainty.",
        ],
    },
    "certifiedGeometry": {
        "asserted_provo": "Derivation",
        "anchors": [
            "Figure this out by verifying that the contraction path exists from source to target.",
            "The certificate is valid because the proof carries a verified contraction path.",
            "The proof is complete when the tree reaches its right-comb normal form.",
            "The contraction path exists and decidable contracts to holds for this tree.",
            "This is correct because the audit channel independently verifies the result.",
            "The result holds because the friction barrier prevents invalid crossings.",
        ],
    },
}

# ═══════════════════════════════════════════════════════════════════════
# 3. Embedding helpers
# ═══════════════════════════════════════════════════════════════════════

EMBED_URL = "http://localhost:8082/v1/embeddings"


def embed_texts(texts: List[str], batch_size: int = 2) -> List[List[float]]:
    """Embed texts via bge-m3 on :8082. Batch size 2 per SAFETY.md INC-1."""
    all_embeddings = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        payload = json.dumps({"input": batch, "max_length": 500}).encode()
        req = urllib.request.Request(
            EMBED_URL,
            data=payload,
            headers={"Content-Type": "application/json"},
        )
        for attempt in range(3):
            try:
                with urllib.request.urlopen(req, timeout=30) as resp:
                    data = json.loads(resp.read())
                all_embeddings.extend(data["data"][j]["embedding"] for j in range(len(batch)))
                break
            except Exception as e:
                if attempt < 2:
                    time.sleep(1)
                else:
                    print(f"  [ERROR] embed batch {i}: {e}")
                    all_embeddings.extend([[0.0] * 1024] * len(batch))
    return all_embeddings


def cosine_sim(a: List[float], b: List[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    na = sum(x * x for x in a) ** 0.5
    nb = sum(y * y for y in b) ** 0.5
    if na == 0 or nb == 0:
        return 0.0
    return dot / (na * nb)


def centroid(embeddings: List[List[float]]) -> List[float]:
    n = len(embeddings)
    if n == 0:
        return [0.0] * 1024
    return [sum(e[i] for e in embeddings) / n for i in range(1024)]


# ═══════════════════════════════════════════════════════════════════════
# 4. Linguistic analysis
# ═══════════════════════════════════════════════════════════════════════

# Simple verb/noun extraction (no spacy dependency — regex-based)
# This is crude but sufficient for pattern analysis

COMMON_VERBS = {
    # Action verbs
    "run", "execute", "parse", "search", "lift", "ground", "build", "compute",
    "produce", "check", "verify", "generate", "transform", "modify", "consume",
    "process", "relocate", "use", "create", "construct", "update", "derive",
    "complete", "start", "end", "invalidate", "associate", "attribute",
    "delegate", "act", "bear", "occur",
    # Cognitive verbs
    "understand", "explore", "investigate", "examine", "study", "look",
    "investigate", "figure", "know", "think", "want", "need", "should",
    "begin", "proceed", "achieve", "intend", "represent", "provides",
    "allow", "indicate", "ascribe", "assign", "carry", "retain",
    # Modal/auxiliary
    "is", "are", "was", "were", "be", "been", "being", "have", "has",
    "had", "do", "does", "did", "will", "would", "can", "could", "may",
    "might", "must", "shall", "should",
}

SCOPING_WORDS = {
    "only", "specific", "precisely", "exactly", "target", "focused",
    "limited", "narrow", "particular", "single", "just", "first",
    "before", "critical", "most",
}

CERTAINTY_WORDS = {
    "definitely", "certainly", "confident", "must", "exactly", "really",
    "certainly", "sure", "right", "correct", "complete", "holds",
    "cannot", "without",
}


def extract_words(text: str) -> List[str]:
    """Extract lowercased words from text."""
    return re.findall(r"[a-zA-Z]+", text.lower())


def analyze_text(text: str) -> Dict[str, Any]:
    """Crude linguistic analysis of a text."""
    words = extract_words(text)
    word_set = set(words)

    # Detect scoping language
    scoping = word_set & SCOPING_WORDS
    # Detect certainty language
    certainty = word_set & CERTAINTY_WORDS
    # Detect action verbs (imperative or gerund)
    action_verbs = word_set & {
        "run", "execute", "parse", "search", "lift", "ground", "build",
        "compute", "produce", "check", "verify", "generate", "transform",
        "modify", "consume", "process", "relocate", "use", "create",
        "construct", "update", "derive", "complete",
    }
    # Detect cognitive verbs
    cognitive_verbs = word_set & {
        "understand", "explore", "investigate", "examine", "study", "look",
        "figure", "know", "think",
    }
    # Detect intent language
    intent_markers = word_set & {
        "let", "should", "need", "will", "must", "intend", "want",
        "begin", "start", "first", "before",
    }
    # Detect first person
    first_person = word_set & {"i", "me", "my", "we", "us", "our"}
    # Detect passive voice markers
    passive = word_set & {"was", "were", "been", "being", "is", "are"}

    # Sentence starts with imperative verb?
    first_word = words[0].lower() if words else ""
    starts_imperative = first_word in action_verbs

    return {
        "word_count": len(words),
        "scoping_words": sorted(scoping),
        "certainty_words": sorted(certainty),
        "action_verbs": sorted(action_verbs),
        "cognitive_verbs": sorted(cognitive_verbs),
        "intent_markers": sorted(intent_markers),
        "first_person": bool(first_person),
        "starts_imperative": starts_imperative,
        "has_passive": bool(passive),
    }


# ═══════════════════════════════════════════════════════════════════════
# 5. Main analysis
# ═══════════════════════════════════════════════════════════════════════

def main():
    print("=" * 78)
    print("PROV-O ↔ Embedding Linguistic Analysis")
    print("=" * 78)

    # ── Phase 1: Linguistic analysis of PROV-O definitions ──────────
    print("\n" + "─" * 78)
    print("PHASE 1: Linguistic patterns in PROV-O class definitions")
    print("─" * 78)

    provo_analysis = {}
    for class_name, info in PROVO_CLASSES.items():
        text = info["definition"]
        analysis = analyze_text(text)
        provo_analysis[class_name] = analysis

    # Print the 6 mapped classes
    mapped_classes = ["Plan", "Activity", "Role", "Entity", "Agent", "Derivation"]
    for cn in mapped_classes:
        a = provo_analysis[cn]
        print(f"\n  prov:{cn}")
        print(f"    Definition: {PROVO_CLASSES[cn]['definition'][:120]}...")
        print(f"    Action verbs: {a['action_verbs']}")
        print(f"    Cognitive verbs: {a['cognitive_verbs']}")
        print(f"    Intent markers: {a['intent_markers']}")
        print(f"    First person: {a['first_person']}")
        print(f"    Starts imperative: {a['starts_imperative']}")
        print(f"    Has passive: {a['has_passive']}")

    # ── Phase 2: Linguistic analysis of our anchors ─────────────────
    print("\n" + "─" * 78)
    print("PHASE 2: Linguistic patterns in CSG anchor texts")
    print("─" * 78)

    anchor_analysis = {}
    for cat_name, info in CSG_CATEGORIES.items():
        all_analyses = [analyze_text(a) for a in info["anchors"]]
        # Aggregate
        all_action = set()
        all_cognitive = set()
        all_scoping = set()
        all_certainty = set()
        all_intent = set()
        first_person_count = 0
        imperative_count = 0
        passive_count = 0
        for a in all_analyses:
            all_action.update(a["action_verbs"])
            all_cognitive.update(a["cognitive_verbs"])
            all_scoping.update(a["scoping_words"])
            all_certainty.update(a["certainty_words"])
            all_intent.update(a["intent_markers"])
            if a["first_person"]:
                first_person_count += 1
            if a["starts_imperative"]:
                imperative_count += 1
            if a["has_passive"]:
                passive_count += 1
        n = len(all_analyses)
        anchor_analysis[cat_name] = {
            "action_verbs": sorted(all_action),
            "cognitive_verbs": sorted(all_cognitive),
            "scoping_words": sorted(all_scoping),
            "certainty_words": sorted(all_certainty),
            "intent_markers": sorted(all_intent),
            "first_person_ratio": first_person_count / n,
            "imperative_ratio": imperative_count / n,
            "passive_ratio": passive_count / n,
        }

    for cat_name in CSG_CATEGORIES:
        a = anchor_analysis[cat_name]
        asserted = CSG_CATEGORIES[cat_name]["asserted_provo"]
        print(f"\n  {cat_name} (asserted → prov:{asserted})")
        print(f"    Action verbs: {a['action_verbs']}")
        print(f"    Cognitive verbs: {a['cognitive_verbs']}")
        print(f"    Scoping words: {a['scoping_words']}")
        print(f"    Certainty words: {a['certainty_words']}")
        print(f"    Intent markers: {a['intent_markers']}")
        print(f"    First person: {a['first_person_ratio']:.0%}")
        print(f"    Starts imperative: {a['imperative_ratio']:.0%}")
        print(f"    Has passive: {a['passive_ratio']:.0%}")

    # ── Phase 3: Embedding similarity ───────────────────────────────
    print("\n" + "─" * 78)
    print("PHASE 3: Embedding space analysis (bge-m3, 1024-dim)")
    print("─" * 78)

    # Prepare all texts to embed
    provo_texts = []
    provo_labels = []
    for cn, info in PROVO_CLASSES.items():
        provo_texts.append(info["definition"])
        provo_labels.append(f"prov:{cn}")

    anchor_texts = []
    anchor_labels = []
    for cat_name, info in CSG_CATEGORIES.items():
        for i, anchor in enumerate(info["anchors"]):
            anchor_texts.append(anchor)
            anchor_labels.append(f"{cat_name}_{i}")

    print(f"\n  Embedding {len(provo_texts)} PROV-O definitions...")
    provo_embs = embed_texts(provo_texts, batch_size=2)
    print(f"  Embedding {len(anchor_texts)} anchor texts...")
    anchor_embs = embed_texts(anchor_texts, batch_size=2)

    # Compute anchor centroids per category
    cat_centroids = {}
    for cat_name in CSG_CATEGORIES:
        cat_embs = []
        for i, label in enumerate(anchor_labels):
            if label.startswith(cat_name + "_"):
                cat_embs.append(anchor_embs[i])
        cat_centroids[cat_name] = centroid(cat_embs)

    # ── Matrix A: Our 6 categories × 6 mapped PROV-O classes ────────
    print("\n  Matrix A: CSG category centroids × mapped PROV-O classes")
    print("  " + "─" * 74)
    mapped = ["Plan", "Activity", "Role", "Entity", "Agent", "Derivation"]
    header = f"  {'Category':22s}"
    for mc in mapped:
        header += f" {mc[:8]:>9s}"
    print(header)
    print("  " + "─" * 74)

    for cat_name in CSG_CATEGORIES:
        row = f"  {cat_name:22s}"
        for mc in mapped:
            mc_idx = provo_labels.index(f"prov:{mc}")
            sim = cosine_sim(cat_centroids[cat_name], provo_embs[mc_idx])
            row += f" {sim:9.3f}"
        asserted = CSG_CATEGORIES[cat_name]["asserted_provo"]
        row += f"  → prov:{asserted}"
        print(row)

    # Mark diagonal (asserted mapping)
    print("  " + "─" * 74)
    print("  (Diagonal = asserted mapping. High diagonal = good alignment.)")

    # ── Matrix B: Our 6 categories × ALL PROV-O classes (nearest) ───
    print("\n  Matrix B: Nearest PROV-O class for each CSG category")
    print("  " + "─" * 74)

    for cat_name in CSG_CATEGORIES:
        sims = []
        for i, label in enumerate(provo_labels):
            sim = cosine_sim(cat_centroids[cat_name], provo_embs[i])
            sims.append((label, sim))
        sims.sort(key=lambda x: -x[1])

        asserted = CSG_CATEGORIES[cat_name]["asserted_provo"]
        asserted_rank = next(
            (i + 1 for i, (label, _) in enumerate(sims)
             if label == f"prov:{asserted}"),
            -1
        )
        asserted_sim = next(
            (sim for label, sim in sims if label == f"prov:{asserted}"),
            0.0
        )

        print(f"\n  {cat_name} (asserted: prov:{asserted}, rank #{asserted_rank}, sim={asserted_sim:.3f})")
        for label, sim in sims[:5]:
            marker = " ◀ ASSERTED" if label == f"prov:{asserted}" else ""
            print(f"    {label:30s}  {sim:.3f}{marker}")

        # Flag mismatch
        if asserted_rank > 3:
            nearest = sims[0][0]
            print(f"    ⚠ MISMATCH: asserted prov:{asserted} is rank #{asserted_rank}")
            print(f"      Nearest is {nearest} (sim={sims[0][1]:.3f})")

    # ── Phase 4: Cross-analysis summary ─────────────────────────────
    print("\n" + "─" * 78)
    print("PHASE 4: Linguistic mismatch summary")
    print("─" * 78)

    mismatches = []

    for cat_name in CSG_CATEGORIES:
        asserted = CSG_CATEGORIES[cat_name]["asserted_provo"]
        a = anchor_analysis[cat_name]
        p = provo_analysis[asserted]

        issues = []

        # Check: anchors use first person but PROV-O doesn't
        if a["first_person_ratio"] > 0.5 and not p["first_person"]:
            issues.append(
                f"Anchors use first-person ({a['first_person_ratio']:.0%}) "
                f"but prov:{asserted} definition does not"
            )

        # Check: anchors start with imperative but PROV-O doesn't
        if a["imperative_ratio"] > 0.3 and not p["starts_imperative"]:
            issues.append(
                f"Anchors start with imperative verbs ({a['imperative_ratio']:.0%}) "
                f"but prov:{asserted} definition does not"
            )

        # Check: anchors use cognitive verbs but PROV-O class has none
        if a["cognitive_verbs"] and not p["cognitive_verbs"]:
            issues.append(
                f"Anchors use cognitive verbs ({a['cognitive_verbs']}) "
                f"but prov:{asserted} definition has none"
            )

        # Check: anchors use scoping words but PROV-O class has none
        if a["scoping_words"] and not p["scoping_words"]:
            issues.append(
                f"Anchors use scoping language ({a['scoping_words']}) "
                f"but prov:{asserted} definition has none"
            )

        # Check: anchors use certainty words but PROV-O class has none
        if a["certainty_words"] and not p["certainty_words"]:
            issues.append(
                f"Anchors use certainty language ({a['certainty_words']}) "
                f"but prov:{asserted} definition has none"
            )

        # Check: PROV-O class uses passive but anchors don't
        if p["has_passive"] and a["passive_ratio"] < 0.3:
            issues.append(
                f"prov:{asserted} definition uses passive voice "
                f"but anchors rarely do ({a['passive_ratio']:.0%})"
            )

        if issues:
            mismatches.append((cat_name, asserted, issues))

    if mismatches:
        for cat_name, asserted, issues in mismatches:
            print(f"\n  ⚠ {cat_name} → prov:{asserted}")
            for issue in issues:
                print(f"      • {issue}")
    else:
        print("\n  No linguistic mismatches detected (all patterns align).")

    # ── Phase 5: Direction analysis ─────────────────────────────────
    print("\n" + "─" * 78)
    print("PHASE 5: Part-of-speech direction analysis")
    print("─" * 78)

    print("""
  PROV-O is a provenance ontology: it describes what HAS HAPPENED.
  Our CSG categories describe what an agent IS DOING (thinking).

  Key tension:
    PROV-O definitions are noun phrases describing THINGS:
      "An activity is something that occurs..."
      "An entity is a physical, digital, conceptual thing..."
      "A plan is an entity that represents..."

  Our anchor texts are verb phrases describing ACTIONS:
      "Run the experiment to compute the result..."
      "Investigate the Tamari lattice..."
      "I really want to make sure..."

  This means the embedding similarity between our anchors and PROV-O
  definitions is measuring cross-directional similarity (verb↔noun),
  which may not reflect the semantic mapping we intend.
""")

    # ── Phase 6: Property-level analysis ────────────────────────────
    print("─" * 78)
    print("PHASE 6: PROV-O property definitions vs VSM systems")
    print("─" * 78)

    # Embed property definitions
    prop_texts = list(PROVO_PROPERTIES.values())
    prop_labels = [f"prov:{k}" for k in PROVO_PROPERTIES.keys()]
    print(f"\n  Embedding {len(prop_texts)} PROV-O property definitions...")
    prop_embs = embed_texts(prop_texts, batch_size=2)

    vsm_to_props = {
        "S1 (Operations)": "used",
        "S2 (Coordination)": "wasInformedBy",
        "S3 (Regulation)": "wasGeneratedBy",
        "S3* (Audit)": "wasDerivedFrom",
        "S4 (Generation)": "hadPlan",
        "S5 (Identity)": "wasAttributedTo",
    }

    print("\n  VSM System → PROV-O property alignment:")
    for vsm, prop in vsm_to_props.items():
        prop_idx = prop_labels.index(f"prov:{prop}")
        # Find nearest property to each anchor centroid
        print(f"\n  {vsm} → prov:{prop}")
        print(f"    Definition: {PROVO_PROPERTIES[prop][:100]}...")

        # Find which category centroid is nearest to this property
        cat_sims = []
        for cat_name in CSG_CATEGORIES:
            sim = cosine_sim(cat_centroids[cat_name], prop_embs[prop_idx])
            cat_sims.append((cat_name, sim))
        cat_sims.sort(key=lambda x: -x[1])
        print(f"    Nearest CSG category: {cat_sims[0][0]} (sim={cat_sims[0][1]:.3f})")
        for cn, sim in cat_sims[:3]:
            marker = " ◀" if cn + "_0" in [al for al in anchor_labels] else ""
            print(f"      {cn:22s} {sim:.3f}")

    # ── Conclusion ──────────────────────────────────────────────────
    print("\n" + "=" * 78)
    print("CONCLUSION")
    print("=" * 78)

    # Find the actual nearest PROV-O class for each category
    print("\n  Corrected mapping (nearest PROV-O class in embedding space):")
    for cat_name in CSG_CATEGORIES:
        asserted = CSG_CATEGORIES[cat_name]["asserted_provo"]
        sims = []
        for i, label in enumerate(provo_labels):
            sim = cosine_sim(cat_centroids[cat_name], provo_embs[i])
            sims.append((label.replace("prov:", ""), sim))
        sims.sort(key=lambda x: -x[1])
        nearest = sims[0][0]
        nearest_sim = sims[0][1]
        asserted_sim = next(s for n, s in sims if n == asserted)
        rank = next(i + 1 for i, (n, s) in enumerate(sims) if n == asserted)

        match = "✓" if nearest == asserted else "✗"
        print(f"    {match} {cat_name:22s}  asserted→prov:{asserted:12s} "
              f"  nearest→prov:{nearest:12s} (sim={nearest_sim:.3f}, "
              f"asserted rank #{rank}, sim={asserted_sim:.3f})")

    print("\n  Key finding: The embedding space reveals that our asserted")
    print("  CSG→PROV-O mapping may not be the nearest neighbor in the")
    print("  embedding space. The linguistic direction mismatch (verb↔noun)")
    print("  means we need to either:")
    print("    a) Rewrite anchors to match PROV-O's definitional style, or")
    print("    b) Accept the mismatch and use PROV-O properties (not classes)")
    print("       as the bridge, since properties describe relations/actions, or")
    print("    c) Use a different ontology that uses process language (e.g. DUL)")
    print("=" * 78)


if __name__ == "__main__":
    main()
