#!/usr/bin/env python3
"""
dat_profile.py — profile a .dat file for gnuplot script generation.

Outputs structured metadata that an agent uses to make informed decisions
about axis ranges, tick spacing, plot type, label placement, and colour
palette selection.

Usage:
    python3 scripts/dat_profile.py plots/advantage_vs_ns.dat
    python3 scripts/dat_profile.py plots/chu_norm.dat

The agent MUST run this on every .dat file before writing a .gnuplot script.
"""

import sys
import numpy as np
from pathlib import Path


def parse_header(path: str) -> tuple[list[str], int]:
    """Parse the comment header(s) and find the first data line."""
    with open(path) as f:
        lines = f.readlines()

    headers = []
    data_start = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith('#'):
            # Collect header text, stripping the # and leading space
            header_text = stripped.lstrip('#').strip()
            if header_text:
                headers.append(header_text)
        elif stripped:
            data_start = i
            break

    return headers, data_start


def profile_file(path: str) -> None:
    """Profile a .dat file and print structured output."""
    path = str(path)
    headers, data_start = parse_header(path)

    # Determine column count from the first data line
    with open(path) as f:
        lines = f.readlines()
    first_data = lines[data_start].strip()
    n_cols_guess = len(first_data.split())

    # Try to load numeric data — skip comment lines automatically
    try:
        data = np.loadtxt(path, comments='#')
    except ValueError:
        # Fallback: load specific columns that are numeric
        # Try loading all columns, skip first if it's a label col
        try:
            data = np.loadtxt(path, comments='#', usecols=range(n_cols_guess))
        except (ValueError, IndexError):
            # Try with usecols that exclude non-numeric columns
            with open(path) as f:
                all_lines = f.readlines()
            # Try column by column
            numeric_cols = []
            for ci in range(n_cols_guess):
                try:
                    col_vals = []
                    for line in all_lines:
                        if line.startswith('#') or not line.strip():
                            continue
                        parts = line.split()
                        if ci < len(parts):
                            col_vals.append(float(parts[ci]))
                    if col_vals:
                        numeric_cols.append(ci)
                except ValueError:
                    continue
            if not numeric_cols:
                print(f"ERROR: {path} has no numeric columns.")
                sys.exit(1)
            data = np.loadtxt(path, comments='#', usecols=numeric_cols)

    n_rows, n_cols = data.shape

    # Resolve column headers from comment header line
    col_headers = []
    for h in headers:
        parts = h.split()
        if len(parts) >= n_cols:
            col_headers = parts[:n_cols]
            break
    if not col_headers:
        # Try last header line
        if headers:
            parts = headers[-1].split()
            if len(parts) >= n_cols:
                col_headers = parts[:n_cols]
    while len(col_headers) < n_cols:
        col_headers.append(f"col{len(col_headers)+1}")

    # ── Print profile ──────────────────────────────────────────────
    print(f"# gnuplot data profile: {path}")
    print(f"# Generated by: python3 scripts/dat_profile.py {path}")
    print()

    # Suggestion for plot type
    print(f"## Summary")
    print(f"  rows = {n_rows}")
    print(f"  cols = {n_cols}")
    print()

    # Plot type suggestion
    print(f"## Plot type suggestion")
    # Check if first column has ≤10 unique integer values → bar chart
    col0 = data[:, 0]
    unique0 = np.unique(col0)
    is_categorical = (len(unique0) <= 12 and
                      np.allclose(col0, col0.astype(int)))
    is_gridded = (n_cols >= 3 and
                  len(np.unique(data[:, 0])) * len(np.unique(data[:, 1])) <= n_rows * 1.1)
    if is_categorical:
        print(f"  bar chart (col1 has {len(unique0)} discrete values)")
    elif is_gridded:
        print(f"  heatmap / pm3d (gridded z = f(x,y))")
    elif n_cols == 2:
        print(f"  single line plot  y = f(x)")
    else:
        print(f"  multi-curve line plot  y_i = f(x) for i=2..{n_cols}")
    print()

    # Column details
    print(f"## Columns")
    for i in range(n_cols):
        col = data[:, i]
        cmin = float(col.min())
        cmax = float(col.max())
        cmn = float(col.mean())
        col_name = col_headers[i] if i < len(col_headers) else f"col{i+1}"

        # Determine type
        uniq = np.unique(col)
        if len(uniq) <= 12 and (n_cols == 1 or np.allclose(col, col.astype(int))):
            ctype = "categorical"
        else:
            ctype = "float"

        print(f"\n  Col {i}:  {col_name}")
        print(f"    range:  [{cmin:.6g}, {cmax:.6g}]")
        print(f"    mean:   {cmn:.6g}")
        print(f"    type:   {ctype}")
        if ctype == "float" and len(col) > 1:
            zero_frac = float((col == 0).mean())
            neg_frac = float((col < 0).mean())
            print(f"    zeros:  {zero_frac*100:.0f}%")
            print(f"    neg:    {neg_frac*100:.0f}%")
        # Suggested axis range with 10% padding
        pad = (cmax - cmin) * 0.1 if cmax > cmin else 1.0
        print(f"    range suggestion:  [{cmin - pad:.6g} : {cmax + pad:.6g}]")

    # Samples
    print(f"\n## Samples")
    print(f"  Head ({min(5, n_rows)}):")
    for r in data[:min(5, n_rows)]:
        fmt = "  " + "  ".join(f"{v:10.6g}" for v in r)
        print(fmt)

    if n_rows > 8:
        print(f"  Tail (3):")
        for r in data[-3:]:
            fmt = "  " + "  ".join(f"{v:10.6g}" for v in r)
            print(fmt)

    # Axis label suggestions from column headers
    print(f"\n## Axis labels")
    if n_cols >= 1:
        print(f"  x:  {col_headers[0]}")
    if n_cols >= 2:
        print(f"  y:  {col_headers[1]}")
    if n_cols >= 3 and not is_gridded:
        print(f"  multi-curve names:  {', '.join(col_headers[1:])}")
    elif n_cols >= 3 and is_gridded:
        print(f"  z:  {col_headers[2]}")

    print()


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 scripts/dat_profile.py <file.dat> [file.dat ...]")
        sys.exit(1)

    for path in sys.argv[1:]:
        if not Path(path).exists():
            print(f"ERROR: file not found: {path}", file=sys.stderr)
            sys.exit(1)
        profile_file(path)


if __name__ == "__main__":
    main()
