#!/usr/bin/env python3
# Regenerate with:
#   python3 scripts/git_archaeology.py > docs/git_archaeology_map.md
"""Git archaeology map: concepts that died in migrations but live on in docs.

For each deleted (git history) or archived (_archive/) .lean file: list its
declarations, keep the ones whose name matches NOTHING in the alive tree
(LaserCortex/), and flag those still cited under docs/. DEAD+CITED rows are
review candidates for concepts that never completed the move to
foundations/ -- name-loss may mean a rename (survived) or a true loss; a
human decides. Matching is by simple name (last dot-segment), which is why
generic words are routed to a STOP review list instead of the main table.
"""
import os, re, subprocess

REPO = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
os.chdir(REPO)

DECL = re.compile(
    r"^(?:private\s+|protected\s+)?(?:theorem|lemma|def|abbrev|inductive|"
    r"structure|class|instance)\s+([\w.\u00c0-\u02ff'?!]+)", re.M)

STOP = {
    'e0', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6', 'e7', 'report', 'apply',
    'append', 'length', 'exactly', 'Chain', 'dedup', 'norm', 'mul', 'size',
    'height', 'step', 'proof', 'test', 'main', 'run', 'eval', 'trace', 'map',
    'filter', 'some', 'none', 'open', 'close', 'cost', 'tree', 'node', 'head',
}

def sh(*a):
    return subprocess.run(a, capture_output=True, text=True).stdout

def read(path):
    try:
        return open(path, encoding='utf8', errors='replace').read()
    except OSError:
        return ''

def alive():
    names, basenames = set(), set()
    for root, _, fs in os.walk('LaserCortex'):
        for f in fs:
            if f.endswith('.lean'):
                basenames.add(f)
                for m in DECL.finditer(read(os.path.join(root, f))):
                    names.add(m.group(1).split('.')[-1])
    return names, basenames

def deleted():
    log = sh('git', 'log', '--diff-filter=D', '--name-only',
             '--pretty=format:@%H|%ad|%s', '--date=short', '--', '*.lean')
    cur, out, seen = None, [], {}
    for line in log.splitlines():
        if line.startswith('@'):
            cur = line[1:].split('|', 2)
        elif line.endswith('.lean') and cur:
            out.append((line, cur))
    for p, c in out:
        seen.setdefault(p, c)  # first hit = newest deletion
    return seen

def citations(symbol):
    g = sh('git', 'grep', '-l', '-w', symbol, '--', 'docs',
           ':(exclude)docs/primer/combined.md',
           ':(exclude)docs/arXiv*', ':(exclude)docs/deep-learning')
    return [l for l in g.split() if l]

def analyze(content, names):
    syms = [m.split('.')[-1] for m in DECL.findall(content)]
    cited, stop_hits = {}, {}
    for x in sorted({s for s in syms if s not in names}):
        fs = citations(x)
        if fs:
            (stop_hits if x in STOP else cited)[x] = fs[:4]
    return len(syms), cited, stop_hits

def main():
    names, basenames = alive()
    print('# Git archaeology map — dead code, live citations')
    print()
    print('Generated by `scripts/git_archaeology.py`. DEAD+CITED = a name')
    print('deleted from the alive tree that docs still cite; check whether the')
    print('concept survived under a new name (rename) or was lost in the port.')
    print()
    print('## Deleted .lean files')
    print()
    for p, (h, d, s) in sorted(deleted().items()):
        moved = 'moved-successor-on-disk' if p.split('/')[-1] in basenames \
            else 'gone'
        ns, cited, stops = analyze(sh('git', 'show', f'{h}^:{p}'), names)
        if cited:
            print(f'### !! {p} [{d}] {moved} :: {s[:70]}')
            for x, fs in cited.items():
                print(f'- `{x}` <- {fs}')
            print()
        else:
            print(f'- {p} [{d}] {moved}: {ns} decls, '
                  f'{len(stops)} generic-word hits only')
    print()
    print('## Archived on disk (_archive/) — unwired, still readable')
    print()
    for dp, _, fs in os.walk('_archive'):
        for f in sorted(fs):
            if not f.endswith('.lean'):
                continue
            path = os.path.join(dp, f)
            ns, cited, stops = analyze(read(path), names)
            if cited:
                print(f'### !! {path}')
                for x, cf in cited.items():
                    print(f'- `{x}` <- {cf}')
                print()
            else:
                print(f'- {path}: {ns} decls, '
                      f'{len(stops)} generic-word hits only')

if __name__ == '__main__':
    main()
