#!/usr/bin/env python3
"""
Log truncation filter: reads full input from stdin, writes ALL of it to a log
file, and outputs only the first N lines, a suppression marker, and the last M
lines to stdout.  Preserves the intended pipeline — the caller can inspect the
log file later with focused tools (grep, read offset/limit).

Usage:
    some-noisy-command 2>&1 | python3 scripts/log-truncate.py [--head 10] [--tail 10] [--log /tmp/foo.log]

Defaults: head=10, tail=10, log=<auto-generated name in /tmp>.
"""

import argparse
import os
import sys
import tempfile
import time

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Truncate verbose program output for context-budget safety."
    )
    parser.add_argument(
        "--head",
        type=int,
        default=10,
        help="Number of leading lines to show (default 10).",
    )
    parser.add_argument(
        "--tail",
        type=int,
        default=10,
        help="Number of trailing lines to show (default 10).",
    )
    parser.add_argument(
        "--log",
        type=str,
        default=None,
        help="Path to write the full log.  Auto-generated in /tmp if omitted.",
    )
    args = parser.parse_args()

    # --- read all input -----------------------------------------------------------
    raw = sys.stdin.buffer.read()
    text = raw.decode("utf-8", errors="replace")
    lines = text.splitlines(keepends=True)
    line_count = len(lines)

    # --- determine log destination ------------------------------------------------
    log_path = args.log
    if log_path is None:
        timestamp = int(time.time() * 1000)
        log_path = os.path.join(
            tempfile.gettempdir(), f"lake-wrap-{timestamp}.log"
        )

    # --- write complete log -------------------------------------------------------
    try:
        with open(log_path, "w", encoding="utf-8") as f:
            f.write(text)
    except OSError as e:
        print(f"log-truncate: WARNING — could not write full log to {log_path}: {e}",
              file=sys.stderr)

    # --- produce truncated output -------------------------------------------------
    n_head = max(args.head, 0)
    n_tail = max(args.tail, 0)

    out = sys.stdout

    if line_count <= n_head + n_tail:
        # Small enough to show entirely
        out.write(text)
    else:
        # Head
        for line in lines[:n_head]:
            out.write(line)
        # Suppression marker
        suppressed = line_count - n_head - n_tail
        marker = f"\n... suppressed {suppressed} lines ...\n\n"
        out.write(marker)
        # Tail
        for line in lines[-n_tail:]:
            out.write(line)

    # --- ensure the last line has a newline ---------------------------------------
    if lines and not lines[-1].endswith("\n"):
        out.write("\n")

    out.flush()

    # --- log tip ------------------------------------------------------------------
    print(f"\n[log-truncate: full log at {log_path}]", file=sys.stderr)


if __name__ == "__main__":
    main()
