#!/usr/bin/env python3
"""PROV-O → Graphiti schema: ingest the W3C provenance ontology as the
typed schema for the CSG → CFG lifting glossary.

Instead of ad-hoc string constants, the glossary is a property graph
whose node labels and edge types come from the W3C PROV-O recommendation
(https://www.w3.org/TR/prov-o/). This gives us:

- Formal semantics (OWL classes and properties)
- Documentation (W3C Recommendation with 10+ years of community use)
- Interoperability (standard provenance model)

The 6 CSG grammar categories map to PROV-O classes:

  temporalMonad      → prov:Plan        (intended set of actions)
  computationAction  → prov:Activity     (action acting on entities)
  scope              → prov:Role         (constraint on the activity)
  exploration        → prov:Entity       (thing being explored/used)
  idempotentTarget   → prov:Agent        (bears responsibility/commitment)
  certifiedGeometry  → prov:Derivation   (certified derivation chain)

The VSM loop maps to PROV-O properties:

  S1 (Operations)    → prov:used            (Activity used Entity)
  S2 (Coordination)  → prov:wasInformedBy   (Activity informed by Activity)
  S3 (Regulation)    → prov:wasGeneratedBy  (Entity generated by Activity)
  S3* (Audit)        → prov:wasDerivedFrom  (Entity derived from Entity)
  S4 (Generation)    → prov:hadPlan         (Association had Plan)
  S5 (Identity)      → prov:wasAttributedTo (Entity attributed to Agent)

Usage:
    python3 scripts/provo_graphiti_schema.py

This creates the schema in the Graphiti graph and stores the 6 categories
as prov:Plan, prov:Activity, prov:Role, prov:Entity, prov:Agent, and
prov:Derivation nodes with their EMLTree shapes and friction costs.
"""
from __future__ import annotations

import asyncio
import json
import os
import sys
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from infra._graphiti_service import GraphitiService

# ═══════════════════════════════════════════════════════════════════════
# PROV-O → CSG category mapping
# ═══════════════════════════════════════════════════════════════════════

PROVO_NS = "http://www.w3.org/ns/prov#"

# The 6 CSG categories mapped to PROV-O classes
CATEGORY_TO_PROVO = {
    "temporalMonad": {
        "provo_class": "Plan",
        "provo_uri": f"{PROVO_NS}Plan",
        "provo_doc": "A set of actions or steps intended by one or more agents to achieve some goals.",
        "tree_shape": "Node(Leaf, Node(Leaf, Leaf))",
        "vsm": "S4",
        "cd_step": 2,
        "anchors": [
            "Let me begin by exploring the problem space and understanding what we are working with.",
            "I should start by taking stock of the current situation before proceeding.",
            "I need to first understand the context and constraints before making changes.",
            "Let us now turn to the next step in the reasoning process.",
            "I will now examine the structure of this problem more carefully.",
        ],
    },
    "computationAction": {
        "provo_class": "Activity",
        "provo_uri": f"{PROVO_NS}Activity",
        "provo_doc": "Something that occurs over a period of time and acts upon or with entities.",
        "tree_shape": "Node(Node(Leaf, Leaf), Leaf)",
        "vsm": "S1",
        "cd_step": 3,
        "anchors": [
            "Run the experiment to compute the result and produce concrete output data.",
            "Execute the verification tool to check whether the certificate contraction path is valid.",
            "Parse the input file and build the output structure from the parsed components.",
            "Search the codebase for all references to this function and list the results.",
            "Lift the inference into the formal layer by calling the bridge lift operation.",
            "Ground the certificate back into the decision layer by decomposing the contraction path.",
        ],
    },
    "scope": {
        "provo_class": "Role",
        "provo_uri": f"{PROVO_NS}Role",
        "provo_doc": "A role is the function of an entity or agent with respect to an activity.",
        "tree_shape": "Node(Leaf, Leaf)",
        "vsm": "S3",
        "cd_step": 1,
        "anchors": [
            "Run a targeted experiment focusing only on the specific module that is failing.",
            "First, check the most critical constraint before expanding the search.",
            "Carefully examine exactly the boundary condition where the error occurs.",
            "Limit the search to precisely the files that were modified in this commit.",
            "Apply this change only to the specific case mentioned, not globally.",
        ],
    },
    "exploration": {
        "provo_class": "Entity",
        "provo_uri": f"{PROVO_NS}Entity",
        "provo_doc": "A physical, digital, conceptual, or other kind of thing with some fixed aspects.",
        "tree_shape": "Node(Node(Leaf, Leaf), Node(Leaf, Leaf))",
        "vsm": "S4",
        "cd_step": 3,
        "anchors": [
            "Investigate the Tamari lattice contraction structure to understand how trees contract.",
            "Explore the proof architecture and understand how the theorems connect to each other.",
            "Understand the codebase structure and how the different modules interact.",
            "Examine what happens when the friction barrier is crossed at the CD 2 to 3 boundary.",
            "Look into the algebraic structure of the split octonion and its basis vectors.",
            "Study how the generation and collapse duality produces candidate structures.",
        ],
    },
    "idempotentTarget": {
        "provo_class": "Agent",
        "provo_uri": f"{PROVO_NS}Agent",
        "provo_doc": "Something that bears some form of responsibility for an activity taking place.",
        "tree_shape": "Leaf",
        "vsm": "S5",
        "cd_step": 0,
        "anchors": [
            "I really want to make sure this is correct before moving forward.",
            "The key insight is definitely that the certificate must verify independently.",
            "This is certainly the right approach because the contraction path is decidable.",
            "I am confident that this result holds and the proof is complete.",
            "This must be exactly right — the system cannot proceed without certainty.",
        ],
    },
    "certifiedGeometry": {
        "provo_class": "Derivation",
        "provo_uri": f"{PROVO_NS}Derivation",
        "provo_doc": "A transformation of an entity into another, using some activity.",
        "tree_shape": "Node(Leaf, Node(Leaf, Node(Leaf, Leaf)))",
        "vsm": "S3*",
        "cd_step": 2,
        "anchors": [
            "Figure this out by verifying that the contraction path exists from source to target.",
            "The certificate is valid because the proof carries a verified contraction path.",
            "The proof is complete when the tree reaches its right-comb normal form.",
            "The contraction path exists and decidable contracts to holds for this tree.",
            "This is correct because the audit channel independently verifies the result.",
            "The result holds because the friction barrier prevents invalid crossings.",
        ],
    },
}

# PROV-O properties that map to VSM systems
VSM_TO_PROVO = {
    "S1": ("used", f"{PROVO_NS}used", "Activity used Entity"),
    "S2": ("wasInformedBy", f"{PROVO_NS}wasInformedBy", "Activity informed by Activity"),
    "S3": ("wasGeneratedBy", f"{PROVO_NS}wasGeneratedBy", "Entity generated by Activity"),
    "S3*": ("wasDerivedFrom", f"{PROVO_NS}wasDerivedFrom", "Entity derived from Entity"),
    "S4": ("hadPlan", f"{PROVO_NS}hadPlan", "Association had Plan"),
    "S5": ("wasAttributedTo", f"{PROVO_NS}wasAttributedTo", "Entity attributed to Agent"),
}

STRUT_WEIGHT = 4
BARRIER = STRUT_WEIGHT * STRUT_WEIGHT


def friction_density(cd_step: int) -> float:
    assoc = 0 if cd_step <= 2 else STRUT_WEIGHT
    return float(cd_step + STRUT_WEIGHT * assoc)


# ═══════════════════════════════════════════════════════════════════════
# Cypher for creating the schema in Graphiti (FalkorDB)
# ═══════════════════════════════════════════════════════════════════════

def build_schema_cypher() -> List[str]:
    """Build Cypher statements to create the PROV-O schema in Graphiti.

    Each CSG category becomes a node with:
    - prov: label (the PROV-O class)
    - csg_category: the category name
    - tree_shape, vsm, cd_step, friction_cost: our properties
    - anchors: the verbose anchor texts

    PROV-O properties become edge types:
    - (:Plan)-[:PRODUCES]->(:Activity)  (temporalMonad → computationAction)
    - (:Activity)-[:USED]->(:Entity)     (computationAction → exploration)
    - (:Activity)-[:HAD_ROLE]->(:Role)   (computationAction → scope)
    - (:Entity)-[:WAS_ATTRIBUTED_TO]->(:Agent)  (exploration → idempotentTarget)
    - (:Entity)-[:WAS_DERIVED_FROM]->(:Derivation)  (exploration → certifiedGeometry)
    """
    statements = []

    # Create category nodes
    for cat_name, info in CATEGORY_TO_PROVO.items():
        provo_class = info["provo_class"]
        gamma = friction_density(info["cd_step"])
        anchors_json = json.dumps(info["anchors"])
        # Escape single quotes in anchors
        anchors_escaped = anchors_json.replace("'", "\\'")

        stmt = (
            f"MERGE (c:{provo_class}:CSGCategory "
            f"{{name: '{cat_name}', provo_class: '{provo_class}', "
            f"provo_uri: '{info['provo_uri']}', "
            f"tree_shape: '{info['tree_shape']}', "
            f"vsm: '{info['vsm']}', "
            f"cd_step: {info['cd_step']}, "
            f"friction_cost: {gamma}, "
            f"provo_doc: '{info['provo_doc'][:200]}'}}) "
            f"SET c.anchors = '{anchors_escaped}'"
        )
        statements.append(stmt)

    # Create VSM system nodes
    for vsm, (prop_name, prop_uri, doc) in VSM_TO_PROVO.items():
        stmt = (
            f"MERGE (v:VSMSystem {{name: '{vsm}', "
            f"provo_property: '{prop_name}', "
            f"provo_uri: '{prop_uri}', "
            f"doc: '{doc}'}})"
        )
        statements.append(stmt)

    # Create edges: category → VSM system (which VSM system governs this category)
    for cat_name, info in CATEGORY_TO_PROVO.items():
        vsm = info["vsm"]
        stmt = (
            f"MATCH (c:CSGCategory {{name: '{cat_name}'}}), "
            f"(v:VSMSystem {{name: '{vsm}'}}) "
            f"MERGE (c)-[:GOVERNED_BY]->(v)"
        )
        statements.append(stmt)

    # Create edges: category → category (the CFG production chain)
    # temporalMonad → computationAction → (scope, exploration) → certifiedGeometry
    # → idempotentTarget
    chain = [
        ("temporalMonad", "computationAction", "PRODUCES"),
        ("computationAction", "scope", "HAS_ROLE"),
        ("computationAction", "exploration", "USED"),
        ("exploration", "certifiedGeometry", "WAS_DERIVED_FROM"),
        ("exploration", "idempotentTarget", "WAS_ATTRIBUTED_TO"),
    ]
    for src, tgt, edge_type in chain:
        stmt = (
            f"MATCH (s:CSGCategory {{name: '{src}'}}), "
            f"(t:CSGCategory {{name: '{tgt}'}}) "
            f"MERGE (s)-[:{edge_type}]->(t)"
        )
        statements.append(stmt)

    return statements


def build_anchor_episodes() -> List[Dict[str, str]]:
    """Build episode data for each anchor text.

    Each anchor becomes an episode in the Graphiti graph, linked to its
    category via the episode body. The embedding server can then compute
    cosine similarities between phrases and these anchor episodes.
    """
    episodes = []
    for cat_name, info in CATEGORY_TO_PROVO.items():
        for i, anchor in enumerate(info["anchors"]):
            episodes.append({
                "name": f"{cat_name}_anchor_{i}",
                "body": anchor,
                "group_id": "provo_schema",
                "source_description": f"prov:{info['provo_class']} anchor for {cat_name}",
                "category": cat_name,
                "provo_class": info["provo_class"],
                "tree_shape": info["tree_shape"],
                "cd_step": info["cd_step"],
            })
    return episodes


async def main():
    print("=" * 70)
    print("PROV-O → Graphiti Schema Ingestion")
    print("=" * 70)

    # Print the mapping
    print("\n─ CSG Category → PROV-O Class mapping ─")
    for cat_name, info in CATEGORY_TO_PROVO.items():
        gamma = friction_density(info["cd_step"])
        print(f"  {cat_name:22s} → prov:{info['provo_class']:15s} "
              f"  {info['tree_shape']:45s}  Γ={gamma:.0f}  {info['vsm']}")

    print("\n─ VSM System → PROV-O Property mapping ─")
    for vsm, (prop, uri, doc) in VSM_TO_PROVO.items():
        print(f"  {vsm:4s} → prov:{prop:20s}  {doc}")

    # Build and execute schema
    print("\n─ Creating schema in Graphiti (FalkorDB) ─")
    service = GraphitiService(db_path="data/provo_glossary.db")

    try:
        await service.start()
        print("  GraphitiService started")

        # Execute schema Cypher
        statements = build_schema_cypher()
        driver = service.driver

        for stmt in statements:
            try:
                await driver.execute_query(stmt)
            except Exception as e:
                print(f"  [SKIP] {stmt[:80]}... — {e}")

        print(f"  Created {len(statements)} schema statements")

        # Verify: count nodes
        result = await driver.execute_query(
            "MATCH (n) RETURN labels(n) as labels, count(n) as count"
        )
        print("\n─ Node count by label ─")
        if result and result[0]:
            for record in result[0]:
                labels = record.get("labels", [])
                count = record.get("count", 0)
                print(f"  {':'.join(labels):40s} {count}")

        # Verify: count edges
        result = await driver.execute_query(
            "MATCH ()-[r]->() RETURN type(r) as type, count(r) as count"
        )
        print("\n─ Edge count by type ─")
        if result and result[0]:
            for record in result[0]:
                edge_type = record.get("type", "")
                count = record.get("count", 0)
                print(f"  {edge_type:40s} {count}")

        # Ingest anchor texts as episodes
        print("\n─ Ingesting anchor texts as episodes ─")
        episodes = build_anchor_episodes()
        for ep in episodes:
            await service.add_episode(
                name=ep["name"],
                body=ep["body"],
                group_id=ep["group_id"],
                source_description=ep["source_description"],
            )
        print(f"  Ingested {len(episodes)} anchor episodes")

        # Show the full glossary graph
        print("\n─ Full glossary graph ─")
        result = await driver.execute_query(
            "MATCH (c:CSGCategory)-[r]->(t) "
            "RETURN c.name as source, type(r) as edge, t.name as target "
            "ORDER BY c.name"
        )
        if result and result[0]:
            for record in result[0]:
                src = record.get("source", "")
                edge = record.get("edge", "")
                tgt = record.get("target", "")
                print(f"  {src:22s} -[:{edge:20s}]-> {tgt}")

        print("\n" + "=" * 70)
        print("Schema ingestion complete.")
        print("The glossary is now a typed PROV-O graph in Graphiti.")
        print("Each CSG category is a prov: class node with its EMLTree shape")
        print("and friction cost. Anchor texts are episodes for embedding.")
        print("=" * 70)

    finally:
        await service.stop()


if __name__ == "__main__":
    asyncio.run(main())
