# quantum_advantage_plots.gnuplot
# Renders 4 separate PNG files from the quantum advantage data.
#
# Usage: gnuplot quantum_advantage_plots.gnuplot
# Requires data files generated by quantum_advantage.py first.

set style data lines
set style fill solid 0.6 border

# ═══════════════════════════════════════════════════════════════════════
# PANEL 1: Friction barrier
# ═══════════════════════════════════════════════════════════════════════
set terminal pngcairo enhanced color font "Sans,12" size 900, 650
set output "../plots/friction_barrier.png"

set title "Friction density  Γ(k)" font "Sans,14"
set xlabel "CD step  k" font "Sans,12" offset 0,-1
set ylabel "Γ(k)" font "Sans,12" offset -1,0
set xrange [-0.5:4.5]
set yrange [0:24]
set xtics ("ℝ" 0, "ℂ" 1, "ℍ" 2, "𝕆ˢ" 3, "𝕊" 4) font "Sans,11"
set grid ytics
set style data boxes

set arrow from 2.2,2 to 2.8,19 nohead lc rgb "#CC3333" lw 2.5 dashtype 2
set label "Γ₃−Γ₂ = 17  (≈ strut_weight² = 16)" at 2.5,10 font "Sans,10" textcolor rgb "#CC3333"
set label "Γ₂ = 2" at 1.6,3.8 font "Sans,11" textcolor rgb "#4066C8"
set label "Γ₃ = 19" at 3.2,20.5 font "Sans,11" textcolor rgb "#4066C8"

plot "../plots/friction_barrier.dat" using 1:2:xtic(3) \
     linecolor rgb "#4066C8" linewidth 3 notitle

# ═══════════════════════════════════════════════════════════════════════
# PANEL 2: Chu pairing norm on S³
# ═══════════════════════════════════════════════════════════════════════
set terminal pngcairo enhanced color font "Sans,12" size 900, 650
set output "../plots/chu_norm.png"

set title "Chu pairing  N(θ) = β(x, S(x))" font "Sans,14"
set xlabel "Mode parameter  θ (rad)" font "Sans,12"
set ylabel "N(θ)  =  a² + b² − c² − d²" font "Sans,12" offset -1,0
set xrange [0:pi]
set yrange [-1.3:1.3]
set xtics ("0" 0, "π/4" pi/4, "π/2" pi/2, "3π/4" 3*pi/4, "π" pi) font "Sans,11"
set grid ytics xtics
unset arrow
unset label

set arrow from pi/2,-1.2 to pi/2,0.05 nohead lc rgb "#CC3333" lw 1.5 dashtype 3
set label "N = 0  (null vector)" at pi/2+0.15,-1.1 font "Sans,10" textcolor rgb "#CC3333"

plot "../plots/chu_norm.dat" using 1:2 linecolor rgb "#228B22" lw 4 \
     title "N(θ) = cos θ", \
     "../plots/chu_norm.dat" using 1:3 linecolor rgb "#228B22" lw 2 dashtype 3 \
     title "|N(θ)|  (effective correlation)"

# ═══════════════════════════════════════════════════════════════════════
# PANEL 3: Quantum advantage vs N_S for various θ
# ═══════════════════════════════════════════════════════════════════════
set terminal pngcairo enhanced color font "Sans,12" size 900, 650
set output "../plots/advantage_curves.png"

set title "Quantum advantage (phase-conjugating receiver)" font "Sans,14"
set xlabel "log₁₀(mean photon number  N_S)" font "Sans,12"
set ylabel "Advantage (dB)" font "Sans,12" offset -1,0
set xrange [-3:2]
set yrange [-0.5:12]
unset arrow
unset label

set key font "Sans,10" spacing 1.3 at graph 0.98,0.02 samplen 2

plot "../plots/advantage_standard.dat" using 1:2 \
     linecolor rgb "#CC3333" lw 4 title "Standard QI  (θ=0, |N|=1)", \
     "../plots/advantage_vs_ns.dat" using 1:2 \
     linecolor rgb "#0000FF" lw 2 title "θ = π/6", \
     "../plots/advantage_vs_ns.dat" using 1:3 \
     linecolor rgb "#4169E1" lw 2 title "θ = π/4", \
     "../plots/advantage_vs_ns.dat" using 1:4 \
     linecolor rgb "#00BFFF" lw 2 title "θ = π/3", \
     "../plots/advantage_vs_ns.dat" using 1:5 \
     linecolor rgb "#32CD32" lw 2 title "θ = π/2"

# Friction headroom reference
friction_db = 10*log10(19.0/2.0)
set arrow from -3,friction_db to 2,friction_db nohead lc rgb "#888888" lw 2.5 dashtype 2
set label "Structural headroom  Γ₃/Γ₂ = 9.8 dB" \
     at -2.9,friction_db+0.9 font "Sans,10" textcolor rgb "#888888"

replot

# ═══════════════════════════════════════════════════════════════════════
# PANEL 4: Combined — heatmap of advantage(N_S, θ)
# ═══════════════════════════════════════════════════════════════════════
set terminal pngcairo enhanced color font "Sans,12" size 900, 650
set output "../plots/advantage_heatmap.png"

set title "Advantage map  dB(θ, N_S)" font "Sans,14"
set xlabel "Mode parameter  θ (rad)" font "Sans,12"
set ylabel "log₁₀(N_S)" font "Sans,12" offset -1,0
set xrange [0:pi]
set yrange [-3:2]
set xtics ("0" 0, "π/4" pi/4, "π/2" pi/2, "3π/4" 3*pi/4, "π" pi) font "Sans,11"
set ytics font "Sans,11"
set grid ytics xtics
unset arrow
unset label

set palette defined ( \
   0 "#FFFFFF", \
   0.3 "#CCE5FF", \
   0.6 "#6699CC", \
   0.9 "#336699", \
   1.5 "#CC3333", \
   2.0 "#990000" )
set cblabel "Advantage (dB)" font "Sans,11"
set cbrange [0:]

plot "../plots/advantage_heatmap.dat" with image notitle
