name: Compile blueprint

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup to free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: false
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Lean project
        uses: leanprover/lean-action@434f25c2f80ded67bba02502ad3a86f25db50709
        with:
          build: true
          lint: false
          mk_all-check: false

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y graphviz libgraphviz-dev

      - name: Install leanblueprint
        run: pip install leanblueprint

      - name: Debug file structure
        run: ls -la blueprint/src/ blueprint/src/macros/

      - name: Build blueprint web
        run: |
          mkdir -p blueprint/web
          plastex -c plastex.cfg web.tex
        working-directory: ./blueprint/src

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './blueprint/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
